name: grafana
version: 1.8.0
appVersion: 5.0.4
description: The leading tool for querying and visualizing time series and metrics.
home: https://grafana.net
icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
sources:
  - https://github.com/grafana/grafana
maintainers:
  - name: Niroop Test
    email: niroop89@gmail.com
  engine: gotpl
